resolver: lts-16.12
packages:
- .
extra-deps:
- git: https://github.com/obsidiansystems/constraints-extras.git
  commit: 72d39c08f7b08a3a756f9019ad972d26a36fbbaa
- dependent-sum-0.7.1.0
- dependent-sum-template-0.1.0.3
- dependent-hashmap-0.1.0.1
- protolude-0.3.0
- rock-0.3.0.0
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
